### PR TITLE
Fix DeckyFront End Errorr by bumping DFL to 3.20.7

### PR DESCRIPTION
**Pull request by JesusRojass**
Fix for [Decky Front End Error #100](https://github.com/NGnius/PowerTools/issues/100) by bumping DFL to 3.20.7

### CODE REVIEW

**Comment by Titaniumtown** [comment]
Please merge! This is the last plugin I have installed that has this issue.

**Comment by JesusRojass** [comment]
Just waiting on approval by @NGnius

**Comment by NGnius** [comment]
LGTM, thanks!

**Comment by NGnius** [comment]
Actually, can you rebase or cherry-pick this into the decky branch too? That way it can be pushed to Decky database too

**Comment by JesusRojass** [comment]
Sure

**Comment by JesusRojass** [comment]
[Done, see PR here](https://github.com/NGnius/PowerTools/pull/104)

**Pull request merged**
